[workspace]
members = [
    "contracts/marketplace",
    "contracts/escrow",
    "contracts/token",
    "integration-tests",
]

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true

[profile.dev]
panic = "abort"